<mxfile host="Electron" modified="2023-04-30T10:10:04.829Z" agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/21.2.1 Chrome/112.0.5615.87 Electron/24.1.2 Safari/537.36" etag="vcSsUENBezS9xpMgjovS" version="21.2.1" type="device">
  <diagram name="第 1 页" id="FBhuhilKmYYwcZSIrgZr">
    <mxGraphModel dx="1288" dy="972" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="827" pageHeight="1169" math="0" shadow="0">
      <root>
        <mxCell id="0" />
        <mxCell id="1" parent="0" />
        <mxCell id="dmTh6fYggep_ElsgC0sf-10" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0;entryY=0.5;entryDx=0;entryDy=0;strokeColor=#6BB5FF;strokeWidth=3;" parent="1" source="dmTh6fYggep_ElsgC0sf-2" target="dmTh6fYggep_ElsgC0sf-7" edge="1">
          <mxGeometry relative="1" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-2" value="main.c" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#6BB5FF;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#FFFFFF;" parent="1" vertex="1">
          <mxGeometry x="240" y="240" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-14" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0;entryY=0.5;entryDx=0;entryDy=0;strokeColor=#6BB5FF;strokeWidth=3;" parent="1" source="dmTh6fYggep_ElsgC0sf-6" target="dmTh6fYggep_ElsgC0sf-13" edge="1">
          <mxGeometry relative="1" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-6" value="f1.c" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#6BB5FF;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#FFFFFF;" parent="1" vertex="1">
          <mxGeometry x="240" y="320" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-17" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0;entryY=0.5;entryDx=0;entryDy=0;strokeColor=#81CCAE;strokeWidth=3;fontFamily=HYYouYuan;fontSize=18;fontColor=#6BB5FF;" parent="1" source="dmTh6fYggep_ElsgC0sf-7" target="dmTh6fYggep_ElsgC0sf-16" edge="1">
          <mxGeometry relative="1" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-7" value="main.o" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#81CCAE;strokeColor=none;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#FFFFFF;" parent="1" vertex="1">
          <mxGeometry x="440" y="240" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-12" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0;entryY=0.5;entryDx=0;entryDy=0;strokeColor=#6BB5FF;strokeWidth=3;" parent="1" source="dmTh6fYggep_ElsgC0sf-11" target="dmTh6fYggep_ElsgC0sf-7" edge="1">
          <mxGeometry relative="1" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-11" value="f1.h" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#6BB5FF;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#FFFFFF;" parent="1" vertex="1">
          <mxGeometry x="240" y="190" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-18" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;strokeColor=#81CCAE;strokeWidth=3;fontFamily=HYYouYuan;fontSize=18;fontColor=#6BB5FF;" parent="1" source="dmTh6fYggep_ElsgC0sf-13" edge="1">
          <mxGeometry relative="1" as="geometry">
            <mxPoint x="640" y="340" as="targetPoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-13" value="f1.o" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#81CCAE;strokeColor=none;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#FFFFFF;" parent="1" vertex="1">
          <mxGeometry x="440" y="320" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-16" value="main" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F57E80;strokeColor=none;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#FFFFFF;" parent="1" vertex="1">
          <mxGeometry x="640" y="320" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-19" value="链接" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;fontFamily=HYYouYuan;fontSize=18;fontStyle=1;fontColor=#81CCAE;" parent="1" vertex="1">
          <mxGeometry x="600" y="280" width="60" height="30" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-23" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0;entryY=0.5;entryDx=0;entryDy=0;strokeColor=#6BB5FF;strokeWidth=3;fontFamily=HYYouYuan;fontSize=18;fontColor=#94EBC8;" parent="1" source="dmTh6fYggep_ElsgC0sf-21" target="dmTh6fYggep_ElsgC0sf-22" edge="1">
          <mxGeometry relative="1" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-21" value="main.c" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#6BB5FF;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#FFFFFF;" parent="1" vertex="1">
          <mxGeometry x="240" y="440" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-22" value="main" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F57E80;strokeColor=none;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#FFFFFF;" parent="1" vertex="1">
          <mxGeometry x="440" y="440" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-24" value="编译、链接" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;fontFamily=HYYouYuan;fontSize=18;fontStyle=1;fontColor=#6BB5FF;" parent="1" vertex="1">
          <mxGeometry x="370" y="420" width="60" height="30" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-25" value="main.c" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="390" y="560" width="90" height="40" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-26" value="main&amp;nbsp;:" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#F57E80;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#F57E80;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="290" y="560" width="90" height="40" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-28" value="gcc main.c -o main" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#81CCAE;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#81CCAE;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="390" y="610" width="220" height="40" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-31" value="目标" style="text;html=1;strokeColor=none;fillColor=#F57E80;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=1;fontSize=16;fontFamily=HYYouYuan;fontColor=#FFFFFF;fontStyle=1" parent="1" vertex="1">
          <mxGeometry x="290" y="530" width="90" height="20" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-32" value="依赖" style="text;html=1;strokeColor=none;fillColor=#6BB5FF;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=1;fontSize=16;fontFamily=HYYouYuan;fontColor=#FFFFFF;fontStyle=1" parent="1" vertex="1">
          <mxGeometry x="390" y="530" width="90" height="20" as="geometry" />
        </mxCell>
        <mxCell id="dmTh6fYggep_ElsgC0sf-33" value="执行语句" style="text;html=1;strokeColor=none;fillColor=#81CCAE;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=1;fontSize=16;fontFamily=HYYouYuan;fontColor=#FFFFFF;fontStyle=1" parent="1" vertex="1">
          <mxGeometry x="520" y="580" width="90" height="20" as="geometry" />
        </mxCell>
        <mxCell id="2RnYh8m3vNNR04iLF3ZO-1" value=": %.c" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=none;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="370" y="720" width="110" height="40" as="geometry" />
        </mxCell>
        <mxCell id="2RnYh8m3vNNR04iLF3ZO-2" value="main" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=none;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#999999;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="320" y="720" width="70" height="40" as="geometry" />
        </mxCell>
        <mxCell id="2RnYh8m3vNNR04iLF3ZO-4" value="目标" style="text;html=1;strokeColor=none;fillColor=#999999;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=1;fontSize=16;fontFamily=HYYouYuan;fontColor=#FFFFFF;fontStyle=1" parent="1" vertex="1">
          <mxGeometry x="290" y="690" width="70" height="20" as="geometry" />
        </mxCell>
        <mxCell id="2RnYh8m3vNNR04iLF3ZO-5" value="依赖" style="text;html=1;strokeColor=none;fillColor=#6BB5FF;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=1;fontSize=16;fontFamily=HYYouYuan;fontColor=#FFFFFF;fontStyle=1" parent="1" vertex="1">
          <mxGeometry x="370" y="690" width="110" height="20" as="geometry" />
        </mxCell>
        <mxCell id="5TOgeOr0YjmLFH-npsvK-1" value="&amp;nbsp;$(foreach" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=none;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;align=center;" parent="1" vertex="1">
          <mxGeometry x="290" y="840" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="5TOgeOr0YjmLFH-npsvK-3" value="dir," style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="420" y="840" width="60" height="40" as="geometry" />
        </mxCell>
        <mxCell id="5TOgeOr0YjmLFH-npsvK-4" value="$(SUBDIR)," style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#F57E80;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#F57E80;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="490" y="840" width="140" height="40" as="geometry" />
        </mxCell>
        <mxCell id="5TOgeOr0YjmLFH-npsvK-5" value="$(dir)/*.c" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="640" y="840" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="5TOgeOr0YjmLFH-npsvK-6" value=")" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=none;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;align=center;" parent="1" vertex="1">
          <mxGeometry x="760" y="840" width="30" height="40" as="geometry" />
        </mxCell>
        <mxCell id="5TOgeOr0YjmLFH-npsvK-9" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=0.5;exitY=0;exitDx=0;exitDy=0;entryX=0.5;entryY=0;entryDx=0;entryDy=0;curved=1;strokeWidth=2;strokeColor=#F57E80;" parent="1" source="5TOgeOr0YjmLFH-npsvK-7" target="5TOgeOr0YjmLFH-npsvK-8" edge="1">
          <mxGeometry relative="1" as="geometry" />
        </mxCell>
        <mxCell id="5TOgeOr0YjmLFH-npsvK-7" value="./func" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#F57E80;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#F57E80;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="570" y="970.0000000000001" width="80" height="40" as="geometry" />
        </mxCell>
        <mxCell id="5TOgeOr0YjmLFH-npsvK-11" style="edgeStyle=orthogonalEdgeStyle;curved=1;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=0.5;exitY=1;exitDx=0;exitDy=0;entryX=0.25;entryY=1;entryDx=0;entryDy=0;strokeColor=#6BB5FF;strokeWidth=2;" parent="1" source="5TOgeOr0YjmLFH-npsvK-8" target="5TOgeOr0YjmLFH-npsvK-10" edge="1">
          <mxGeometry relative="1" as="geometry">
            <Array as="points">
              <mxPoint x="530" y="1070.0900000000001" />
              <mxPoint x="690" y="1070.0900000000001" />
            </Array>
          </mxGeometry>
        </mxCell>
        <mxCell id="5TOgeOr0YjmLFH-npsvK-8" value="dir" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="500" y="1000.0600000000001" width="60" height="40" as="geometry" />
        </mxCell>
        <mxCell id="5TOgeOr0YjmLFH-npsvK-10" value="$(dir)/*.c" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="660" y="1000.0600000000001" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="5TOgeOr0YjmLFH-npsvK-28" value="" style="shape=flexArrow;endArrow=classic;html=1;rounded=0;strokeColor=#999999;strokeWidth=2;" parent="1" edge="1">
          <mxGeometry width="50" height="50" relative="1" as="geometry">
            <mxPoint x="481" y="1019.83" as="sourcePoint" />
            <mxPoint x="434" y="1019.7700000000001" as="targetPoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="5TOgeOr0YjmLFH-npsvK-32" value="./func/*.c" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#81CCAE;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#81CCAE;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="300" y="970.0000000000001" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="5TOgeOr0YjmLFH-npsvK-33" value="." style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#F57E80;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#F57E80;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="570" y="1020.0000000000001" width="80" height="40" as="geometry" />
        </mxCell>
        <mxCell id="5TOgeOr0YjmLFH-npsvK-34" value="./*.c" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#81CCAE;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#81CCAE;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="300" y="1020.0000000000001" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="5TOgeOr0YjmLFH-npsvK-35" value="" style="shape=flexArrow;endArrow=classic;html=1;rounded=0;strokeColor=#999999;strokeWidth=2;" parent="1" edge="1">
          <mxGeometry width="50" height="50" relative="1" as="geometry">
            <mxPoint x="529.71" y="900" as="sourcePoint" />
            <mxPoint x="529.71" y="939.94" as="targetPoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-1" value="&amp;nbsp; // 函数声明&lt;br&gt;&amp;nbsp; void Print_Progress_Bar(float comp);" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;align=left;" parent="1" vertex="1">
          <mxGeometry x="960" y="640" width="560" height="80" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-5" value="写法" style="text;html=1;strokeColor=none;fillColor=#6BB5FF;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=1;fontSize=16;fontFamily=HYYouYuan;fontColor=#FFFFFF;fontStyle=1" parent="1" vertex="1">
          <mxGeometry x="300" y="810" width="110" height="20" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-6" value="&lt;div&gt;&amp;nbsp; #include &amp;lt;stdio.h&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; #include &quot;bar.h&quot;&lt;/div&gt;&lt;div&gt;&amp;nbsp;&amp;nbsp;&lt;/div&gt;&lt;div&gt;&amp;nbsp; int main(void)&lt;/div&gt;&lt;div&gt;&amp;nbsp; {&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; printf(&quot;Hello from new main!\n&quot;);&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; Print_Progress_Bar(33.0f/100.0f);&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; return 0;&lt;/div&gt;&lt;div&gt;&amp;nbsp; }&lt;/div&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;align=left;" parent="1" vertex="1">
          <mxGeometry x="960" y="770" width="560" height="290" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-7" value="通用写法" style="text;html=1;strokeColor=none;fillColor=#6BB5FF;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=1;fontSize=16;fontFamily=HYYouYuan;fontColor=#FFFFFF;fontStyle=1" parent="1" vertex="1">
          <mxGeometry x="190" y="1190" width="140" height="20" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-8" value="" style="shape=flexArrow;endArrow=classic;html=1;rounded=0;strokeColor=#F57E80;strokeWidth=2;endWidth=94.86111111111111;endSize=9.658333333333333;width=45.833333333333336;" parent="1" edge="1">
          <mxGeometry width="50" height="50" relative="1" as="geometry">
            <mxPoint x="1550" y="869.64" as="sourcePoint" />
            <mxPoint x="1590" y="869.58" as="targetPoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-9" value="&lt;div&gt;&amp;nbsp; #include &amp;lt;stdio.h&amp;gt;&lt;/div&gt;&lt;div&gt;&lt;font color=&quot;#f57e80&quot;&gt;&amp;nbsp;&lt;/font&gt; // 函数声明&lt;/div&gt;&lt;div&gt;&amp;nbsp; void Print_Progress_Bar(float comp);&lt;/div&gt;&lt;div&gt;&amp;nbsp;&amp;nbsp;&lt;/div&gt;&lt;div&gt;&amp;nbsp; int main(void)&lt;/div&gt;&lt;div&gt;&amp;nbsp; {&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; printf(&quot;Hello from new main!\n&quot;);&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; Print_Progress_Bar(33.0f/100.0f);&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; return 0;&lt;/div&gt;&lt;div&gt;&amp;nbsp; }&lt;/div&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#F57E80;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#F57E80;dashed=1;strokeWidth=2;align=left;" parent="1" vertex="1">
          <mxGeometry x="1610" y="640" width="560" height="420" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-10" value="entry.i" style="text;html=1;strokeColor=none;fillColor=#F57E80;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=1;fontSize=16;fontFamily=HYYouYuan;fontColor=#FFFFFF;fontStyle=1" parent="1" vertex="1">
          <mxGeometry x="1610" y="610" width="110" height="20" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-13" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0;entryY=0.5;entryDx=0;entryDy=0;strokeColor=#6BB5FF;strokeWidth=3;" parent="1" source="TkIjqa0i_HGDWWnGM9GY-14" target="TkIjqa0i_HGDWWnGM9GY-18" edge="1">
          <mxGeometry relative="1" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-14" value="entry.c" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#6BB5FF;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#FFFFFF;" parent="1" vertex="1">
          <mxGeometry x="820" y="240" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-15" style="edgeStyle=orthogonalEdgeStyle;rounded=0;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0;entryY=0.5;entryDx=0;entryDy=0;strokeColor=#6BB5FF;strokeWidth=3;" parent="1" source="TkIjqa0i_HGDWWnGM9GY-16" target="TkIjqa0i_HGDWWnGM9GY-22" edge="1">
          <mxGeometry relative="1" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-16" value="bar.c" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#6BB5FF;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#FFFFFF;" parent="1" vertex="1">
          <mxGeometry x="820" y="320" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-17" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0;entryY=0.5;entryDx=0;entryDy=0;strokeColor=#81CCAE;strokeWidth=3;fontFamily=HYYouYuan;fontSize=18;fontColor=#81CCAE;" parent="1" source="TkIjqa0i_HGDWWnGM9GY-18" target="TkIjqa0i_HGDWWnGM9GY-23" edge="1">
          <mxGeometry relative="1" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-18" value="main.o" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#999999;strokeColor=none;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#FFFFFF;" parent="1" vertex="1">
          <mxGeometry x="1020" y="240" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-19" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;entryX=0;entryY=0.5;entryDx=0;entryDy=0;strokeColor=#6BB5FF;strokeWidth=3;" parent="1" source="TkIjqa0i_HGDWWnGM9GY-20" target="TkIjqa0i_HGDWWnGM9GY-18" edge="1">
          <mxGeometry relative="1" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-20" value="bar.h" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#6BB5FF;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#FFFFFF;" parent="1" vertex="1">
          <mxGeometry x="820" y="190" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-21" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;exitX=1;exitY=0.5;exitDx=0;exitDy=0;strokeColor=#81CCAE;strokeWidth=3;fontFamily=HYYouYuan;fontSize=18;fontColor=#81CCAE;" parent="1" source="TkIjqa0i_HGDWWnGM9GY-22" edge="1">
          <mxGeometry relative="1" as="geometry">
            <mxPoint x="1220" y="340" as="targetPoint" />
          </mxGeometry>
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-22" value="bar.o" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#999999;strokeColor=none;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#FFFFFF;" parent="1" vertex="1">
          <mxGeometry x="1020" y="320" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-23" value="main" style="rounded=1;whiteSpace=wrap;html=1;fillColor=#F57E80;strokeColor=none;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#FFFFFF;" parent="1" vertex="1">
          <mxGeometry x="1220" y="320" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-24" value="链接" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;fontFamily=HYYouYuan;fontSize=18;fontStyle=1;fontColor=#81CCAE;" parent="1" vertex="1">
          <mxGeometry x="1180" y="280" width="60" height="30" as="geometry" />
        </mxCell>
        <mxCell id="TkIjqa0i_HGDWWnGM9GY-25" value="编译" style="text;html=1;strokeColor=none;fillColor=none;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=0;fontFamily=HYYouYuan;fontSize=18;fontStyle=1;fontColor=#6BB5FF;" parent="1" vertex="1">
          <mxGeometry x="950" y="280" width="60" height="30" as="geometry" />
        </mxCell>
        <mxCell id="_krDD5OlNL2HFM5RRQN2-1" value="&lt;div&gt;&amp;nbsp; &lt;font color=&quot;#81ccae&quot;&gt;%.o&lt;/font&gt; : &lt;font color=&quot;#f57e80&quot;&gt;%.c&lt;/font&gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &lt;font color=&quot;#999999&quot;&gt;gcc -c $(INCS)&lt;/font&gt; &lt;font color=&quot;#f57e80&quot;&gt;$&amp;lt;&lt;/font&gt; &lt;font color=&quot;#999999&quot;&gt;-o&lt;/font&gt; &lt;font color=&quot;#81ccae&quot;&gt;$@&lt;/font&gt;&lt;/div&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;align=left;" parent="1" vertex="1">
          <mxGeometry x="190" y="1220" width="550" height="80" as="geometry" />
        </mxCell>
        <mxCell id="_krDD5OlNL2HFM5RRQN2-3" value="展开结果" style="text;html=1;strokeColor=none;fillColor=#81CCAE;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=1;fontSize=16;fontFamily=HYYouYuan;fontColor=#FFFFFF;fontStyle=1" parent="1" vertex="1">
          <mxGeometry x="300" y="940" width="110" height="20" as="geometry" />
        </mxCell>
        <mxCell id="_krDD5OlNL2HFM5RRQN2-5" value="展开结果" style="text;html=1;strokeColor=none;fillColor=#81CCAE;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=1;fontSize=16;fontFamily=HYYouYuan;fontColor=#FFFFFF;fontStyle=1" parent="1" vertex="1">
          <mxGeometry x="190" y="1310" width="140" height="20" as="geometry" />
        </mxCell>
        <mxCell id="_krDD5OlNL2HFM5RRQN2-6" value="&lt;div&gt;&amp;nbsp; ./entry.o : &lt;font color=&quot;#f57e80&quot;&gt;./entry.c&lt;/font&gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &lt;font color=&quot;#999999&quot;&gt;gcc -c $(INCS)&lt;/font&gt; &lt;font color=&quot;#f57e80&quot;&gt;./entry.c&lt;/font&gt;&amp;nbsp;&lt;font color=&quot;#999999&quot;&gt;-o&lt;/font&gt; ./entry.o&lt;/div&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#81CCAE;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#81CCAE;dashed=1;strokeWidth=2;align=left;" parent="1" vertex="1">
          <mxGeometry x="190" y="1340" width="550" height="80" as="geometry" />
        </mxCell>
        <mxCell id="_krDD5OlNL2HFM5RRQN2-8" value="&lt;font face=&quot;HYYouYuan&quot;&gt;···&lt;/font&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#81CCAE;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#81CCAE;dashed=1;strokeWidth=2;align=center;" parent="1" vertex="1">
          <mxGeometry x="190" y="1430" width="550" height="30" as="geometry" />
        </mxCell>
        <mxCell id="_krDD5OlNL2HFM5RRQN2-9" value="&amp;nbsp;$(patsubst" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=none;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;align=center;" parent="1" vertex="1">
          <mxGeometry x="960" y="1230" width="120" height="40" as="geometry" />
        </mxCell>
        <mxCell id="_krDD5OlNL2HFM5RRQN2-10" value="%.o," style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#81CCAE;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#81CCAE;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="1160" y="1230" width="60" height="40" as="geometry" />
        </mxCell>
        <mxCell id="_krDD5OlNL2HFM5RRQN2-11" value="%.c," style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#F57E80;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#F57E80;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="1090" y="1230" width="60" height="40" as="geometry" />
        </mxCell>
        <mxCell id="_krDD5OlNL2HFM5RRQN2-12" value="$(SRCS)" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#6BB5FF;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;" parent="1" vertex="1">
          <mxGeometry x="1230" y="1230" width="110" height="40" as="geometry" />
        </mxCell>
        <mxCell id="_krDD5OlNL2HFM5RRQN2-13" value=")" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=none;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;align=center;" parent="1" vertex="1">
          <mxGeometry x="1350" y="1230" width="30" height="40" as="geometry" />
        </mxCell>
        <mxCell id="_krDD5OlNL2HFM5RRQN2-14" value="写法" style="text;html=1;strokeColor=none;fillColor=#6BB5FF;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=1;fontSize=16;fontFamily=HYYouYuan;fontColor=#FFFFFF;fontStyle=1" parent="1" vertex="1">
          <mxGeometry x="970" y="1200" width="110" height="20" as="geometry" />
        </mxCell>
        <mxCell id="_krDD5OlNL2HFM5RRQN2-15" value="&amp;nbsp;&lt;font color=&quot;#999999&quot;&gt;./entry&lt;/font&gt;&lt;font color=&quot;#f57e80&quot;&gt;.c&lt;/font&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#F57E80;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;align=left;" parent="1" vertex="1">
          <mxGeometry x="970" y="1320" width="130" height="40" as="geometry" />
        </mxCell>
        <mxCell id="_krDD5OlNL2HFM5RRQN2-16" value="&lt;font color=&quot;#999999&quot;&gt;./func/bar&lt;/font&gt;&lt;font color=&quot;#f57e80&quot;&gt;.c&lt;/font&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#F57E80;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;align=center;" parent="1" vertex="1">
          <mxGeometry x="1110" y="1320" width="170" height="40" as="geometry" />
        </mxCell>
        <mxCell id="_krDD5OlNL2HFM5RRQN2-17" value="$(SRCS)" style="text;html=1;strokeColor=none;fillColor=#F57E80;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=1;fontSize=16;fontFamily=HYYouYuan;fontColor=#FFFFFF;fontStyle=1" parent="1" vertex="1">
          <mxGeometry x="970" y="1290" width="110" height="20" as="geometry" />
        </mxCell>
        <mxCell id="_utDKyFxTzlAmGBQsjGk-2" value="bar.h" style="text;html=1;strokeColor=none;fillColor=#6BB5FF;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=1;fontSize=16;fontFamily=HYYouYuan;fontColor=#FFFFFF;fontStyle=1" vertex="1" parent="1">
          <mxGeometry x="960" y="610" width="110" height="20" as="geometry" />
        </mxCell>
        <mxCell id="_utDKyFxTzlAmGBQsjGk-3" value="entry.c" style="text;html=1;strokeColor=none;fillColor=#6BB5FF;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=1;fontSize=16;fontFamily=HYYouYuan;fontColor=#FFFFFF;fontStyle=1" vertex="1" parent="1">
          <mxGeometry x="960" y="740" width="110" height="20" as="geometry" />
        </mxCell>
        <mxCell id="_utDKyFxTzlAmGBQsjGk-4" value="&amp;nbsp;&lt;font color=&quot;#999999&quot;&gt;./entry&lt;/font&gt;&lt;font color=&quot;#81ccae&quot;&gt;.o&lt;/font&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#81CCAE;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;align=left;" vertex="1" parent="1">
          <mxGeometry x="970" y="1410" width="130" height="40" as="geometry" />
        </mxCell>
        <mxCell id="_utDKyFxTzlAmGBQsjGk-5" value="&lt;font color=&quot;#999999&quot;&gt;./func/bar&lt;/font&gt;&lt;font color=&quot;#81ccae&quot;&gt;.o&lt;/font&gt;" style="rounded=1;whiteSpace=wrap;html=1;fillColor=none;strokeColor=#81CCAE;fontStyle=1;fontFamily=Comic Sans MS;fontSize=22;fontColor=#6BB5FF;dashed=1;strokeWidth=2;align=center;" vertex="1" parent="1">
          <mxGeometry x="1110" y="1410" width="170" height="40" as="geometry" />
        </mxCell>
        <mxCell id="_utDKyFxTzlAmGBQsjGk-6" value="展开结果" style="text;html=1;strokeColor=none;fillColor=#81CCAE;align=center;verticalAlign=middle;whiteSpace=wrap;rounded=1;fontSize=16;fontFamily=HYYouYuan;fontColor=#FFFFFF;fontStyle=1" vertex="1" parent="1">
          <mxGeometry x="970" y="1380" width="110" height="20" as="geometry" />
        </mxCell>
        <mxCell id="_utDKyFxTzlAmGBQsjGk-7" value="" style="html=1;shadow=0;dashed=0;align=center;verticalAlign=middle;shape=mxgraph.arrows2.uTurnArrow;dy=8.64;arrowHead=43;dx2=25;rotation=-180;strokeColor=#81CCAE;fillColor=#81CCAE;" vertex="1" parent="1">
          <mxGeometry x="1300" y="1330" width="70" height="120" as="geometry" />
        </mxCell>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
